name: flutter_eval
description: Flutter bridge library for dart_eval, enabling creation of fully dynamic Flutter apps and widgets that can be loaded from a file or the Internet at runtime.
version: 0.6.1+1
homepage: https://github.com/ethanblake4/flutter_eval

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_eval: ^0.6.1
  path_provider: ^2.0.11
  http: ^1.0.0

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
    
flutter:
