name: code_push_app
description: Sample app demonstrating the use of flutter_eval for code push.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_eval: ^0.6.0
  dart_eval: ^0.6.0
dev_dependencies:
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
