name: hot_update
description: Hot update package for code_push_app.
version: 0.6.0
homepage:

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  eval_annotation: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

